version: 2
jobs:
  build:
    machine: true
    resource_class: medium
    working_directory: ~/repo
    environment:
      _JAVA_OPTIONS: "-Xmx6400m"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      GRAALVM_HOME: /home/circleci/repo/.graalvm
    steps:
      - run:
          name: Install OpenJDK 11
          command: |
            sudo apt-get update && sudo apt-get install openjdk-11-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-11-openjdk-amd64/bin/javac
            java -version
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
      - run:
          name: Install dependencies
          command: ./gradlew build -x test
      - save_cache:
          paths:
            - ~/repo/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/repo/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
      - run:
          name: Run tests
          command: ./gradlew test
      - run:
          name: Install GraalVM
          command: curl https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-20.2.0/graalvm-ce-java11-linux-amd64-20.2.0.tar.gz -O -J -L && tar xfz graalvm-ce-java11-linux-amd64-20.2.0.tar.gz && mv graalvm-ce-java11-20.2.0 .graalvm && rm graalvm-ce-java11-linux-amd64-20.2.0.tar.gz
      - run:
          name: Install native-image
          command: $GRAALVM_HOME/bin/gu install native-image
      - run:
          name: Verify (Native)
          command: ./gradlew build -Dquarkus.package.type=native
          no_output_timeout: 30m
      - run:
          name: Verify (Native)
          command: ./gradlew testNative -i
          no_output_timeout: 30m
